27 order service
MartsTech/Aeon pull request #69
Opened 2023-04-21 20:48 UTC by SavinaMih

2023-04-21 21:57 UTC, MartsTech requested changes

2023-04-21 21:57 UTC, MartsTech commented on src/Services/Catalog/src/Catalog.Persistence/Catalog.Persistence.csproj
> +    <PackageReference Include="BuildingBlocks.Common" Version="1.0.0.65" />
This packages does not belog here at all. Why change the catalog service?

2023-04-21 21:57 UTC, MartsTech commented on src/Services/Catalog/src/Catalog.Domain/Catalog.Domain.csproj
> +    <PackageReference Include="BuildingBlocks.Common" Version="1.0.0.65" />
This packages does not belog here at all. Why change the catalog service?

2023-04-21 21:57 UTC, MartsTech commented on src/Services/Catalog/src/Catalog.Application/Catalog.Application.csproj
> +    <PackageReference Include="BuildingBlocks.Common" Version="1.0.0.65" />
This packages does not belog here at all. Why change the catalog service?

2023-04-21 21:57 UTC, MartsTech commented on src/Services/Catalog/src/Catalog.Api/Catalog.Api.csproj
> +    <PackageReference Include="BuildingBlocks.Common" Version="1.0.0.65" />
This packages does not belog here at all. Why change the catalog service?

2023-04-21 21:57 UTC, MartsTech commented on src/Services/Bookmarks/src/Bookmarks.Persistence/Bookmarks.Persistence.csproj
> +    <PackageReference Include="BuildingBlocks.Common" Version="1.0.0.65" />
This packages does not belog here at all. Why change the bookmarks service?

2023-04-21 21:57 UTC, MartsTech commented on src/Services/Bookmarks/src/Bookmarks.Domain/Bookmarks.Domain.csproj
> +    <PackageReference Include="BuildingBlocks.Common" Version="1.0.0.65" />
This packages does not belog here at all. Why change the bookmarks service?

2023-04-21 21:57 UTC, MartsTech commented on src/Services/Bookmarks/src/Bookmarks.Application/Bookmarks.Application.csproj
> +    <PackageReference Include="BuildingBlocks.Common" Version="1.0.0.65" />
This packages does not belog here at all. Why change the bookmarks service?

2023-04-21 21:57 UTC, MartsTech commented on src/Services/Bookmarks/src/Bookmarks.Api/Bookmarks.Api.csproj
> +    <PackageReference Include="BuildingBlocks.Common" Version="1.0.0.65" />
This packages does not belog here at all. Why change the bookmarks service?

2023-04-21 21:57 UTC, MartsTech commented on src/BuildingBlocks/BuildingBlocks.csproj
> +      <PackageReference Include="BuildingBlocks.Common" Version="1.0.0.65" />
There should have been no need for additional packages. At least Microsoft.Tpl.Dataflow is very unnecessary

2023-04-21 21:57 UTC, MartsTech commented on src/ApiGateway/src/ApiGateway.csproj
> +      <PackageReference Include="BuildingBlocks.Common" Version="1.0.0.65" />
This packages does not belog here at all. Why change the api-gateway service?

2023-04-21 21:57 UTC, MartsTech commented on OrderService.Api/OrderLists/GetOrderList/GetOrderListController.cs
> +        [HttpGet("{includeBookmarks:bool}")]
There are no bookmarks in this service

2023-04-21 21:57 UTC, MartsTech commented on OrderService.Api/OrderLists/GetOrderList/GetOrderListController.cs
> +        public async Task<IActionResult> GetAllOrderists()
Typo

2023-04-21 21:57 UTC, MartsTech commented on OrderService.Api/OrderLists/GetOrderList/GetOrderListController.cs
> +        public async Task<IActionResult> GetAllWishlists(bool includeProducts)
Wishlists and includeProducts?

2023-04-21 21:57 UTC, MartsTech commented on OrderService.Api/OrderLists/AddOrderList/AddOrderListController.cs
> +            Result<WishlistDto> result = await Mediator.Send(new AddOrderListCommand.Command(input));
WishlistDto?

2023-04-21 21:57 UTC, MartsTech commented on OrderService.Api/OrderLists/GetOrderList/GetOrderListController.cs
> +    public class GetWishlistsController : UserController
GetWishlistController?

2023-04-21 21:57 UTC, MartsTech commented on OrderService.Api/OrderLists/DeleteOrderList/DeleteOrderListConsumer.cs
> +            _logger.LogInformation("Wishlist deleted with ID: {MessageId}", context.Message.Id);
Wishlist?

2023-04-21 21:57 UTC, MartsTech commented on OrderService.Api/Order/AddOrder/AddOrderConsumer.cs
> +public class AddBookmarkConsumer : IConsumer<OrderCreated>
BookmarkConsumer?

2023-04-21 21:57 UTC, MartsTech commented on OrderService.Api/Program.cs
> +    var context = services.GetRequiredService<BookmarksDbContext>();
Bookmarks?

2023-04-21 21:57 UTC, MartsTech commented on OrderService.Api/Program.cs
> +using Bookmarks.Api.Extensions;
Bookmarks???

2023-04-21 21:57 UTC, MartsTech commented on OrderService.Domain/Orders/IOrderRepository.cs
> +        Task<bool> Deleteorder(Guid id, Guid userId);
Typo

2023-04-22 07:50 UTC, bdbelchev requested changes
In addition to the issues already pointed out, I noticed the directory structure is incorrect, as the project files and directories should be located in src/Services/...

Also, there are some leftover namespaces from the Bookmarks service, as well as some usage of its entities. A good way to check would be to remove every `using` declaration that references Bookmarks, and check if there are errors. That way you will quickly know where you are referencing classes that belong to other projects.

2023-04-22 07:50 UTC, bdbelchev commented on OrderService.Application/OrderList/GetList/GetListByIdQuery.cs
> +                return Result<WishlistDto>.Failure("No user id found");
This is the wishlist DTO.

2023-04-22 07:50 UTC, bdbelchev commented on OrderService.Application/Orders/DeleteOrder/DeleteOrderCommand.cs
> +public sealed class DeleteBookmarkCommand
```suggestion
public sealed class DeleteOrderCommand
```

2023-04-22 07:50 UTC, bdbelchev commented on OrderService.Domain/Orders/IOrder.cs
> +    public interface IBookmark
```suggestion
    public interface IOrder
```

2023-04-22 07:50 UTC, bdbelchev commented on OrderService.Persistence/OrderLists/OrderListConfiguration.cs
> +namespace Bookmarks.Persistence.Wishlists
Leftover namespace from other project.

2023-04-22 07:50 UTC, bdbelchev commented on OrderService.Persistence/OrderLists/OrderListRepository.cs
> +namespace Bookmarks.Persistence.Wishlists
Leftover namespace.

2023-04-22 07:50 UTC, bdbelchev commented on OrderService.Persistence/Orders/OrderRepository.cs
> +using Bookmarks.Persistence.Wishlists;
```suggestion
```

2023-04-22 07:50 UTC, bdbelchev commented on OrderService.Persistence/OrdersDbContext.cs
I'm not sure we should depend on classes from the other service. Also, this is not CatalogDBContext, and I don't see why we should add DbSets for Products.

2023-04-22 07:50 UTC, bdbelchev commented on OrderService.Persistence/UnitOfWork.cs
> +    private readonly CatalogDbContext _context;
Maybe OrdersDbContext?

2023-04-30 19:43 UTC, closed without merging