22 cart service
MartsTech/Aeon pull request #71
Opened 2023-04-22 13:07 UTC by SavinaMih

2023-04-22 14:38 UTC, MartsTech requested changes

2023-04-22 14:38 UTC, MartsTech commented on ShoppingCart.Api/Program.cs
> +    var context = services.GetRequiredService<CatalogDbContext>();
CatalogDbContext?

2023-04-22 14:38 UTC, MartsTech commented on ShoppingCart.Api/ShoppingCarts/CreateShoppingCart/CreateShoppingCartConsumer.cs
> +    public AddCategoryConsumer(ILogger<AddShoppingCartConsumer> logger)
Constructure name does not match files

2023-04-23 06:06 UTC, bdbelchev requested changes
I noticed you are referencing Product and ProductDto. Each microservice should be independent from the others and not know of their existence. This could be accomplished by using just the ID as a foreign key. You can use the Bookmark entity in the Bookmarks service as a reference - it does not reference the products directly.

2023-04-30 19:43 UTC, closed without merging